version: '3.8'

services:
  # Yii2 application service
  web:
    image: yiisoftware/yii2-php-apache:latest
    container_name: yii2-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2_db
      MYSQL_USER: yii2_user
      MYSQL_PASSWORD: yii2_pass
    depends_on:
      - db

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: yii2-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2_db
      MYSQL_USER: yii2_user
      MYSQL_PASSWORD: yii2_pass
    volumes:
      - yii2-db-data:/var/lib/mysql

volumes:
  yii2-db-data: