# docker-stack.yml

version: '3.8'

services:
  yii2_app:
    image: yourdockerhubusername/yii2_app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - yii2net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /path/to/your/yii2-app:/var/www/html
      - /path/to/your/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - yii2_app
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - yii2net

networks:
  yii2net:
    driver: overlay
