version: '3.7'

services:
  yii2-app:
    image: yii2-app:latest
    build: .
    ports:
      - "8080:80"
    networks:
      - appnet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  appnet:
    driver: overlay
